ARG JUPBC
FROM ${JUPBC}

# bypassing ARG for JUID/JGID for Unraid, to use its default user
USER root
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    (addgroup --group --gid 100 jupyter || true) && \
    adduser --force-badname --disabled-password --gecos '' --uid 99 --gid 100 --shell /bin/bash jupyter && \
    adduser jupyter sudo 

USER jupyter
RUN sudo chown -R jupyter /home/jupyter /iti

WORKDIR /iti

EXPOSE 8888

# Adding a default token 
CMD jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --IdentityProvider.token='iti'